### ISSUE TITLE
Update peerDependencies

### ISSUE THREAD

**Issue by realHablex** [hassam7/ngx-focus-trap#2]
Hi Hassam,

Can you please update the peerDependencies of this to include Angular 8 and Angular 9?

**Comment by hassam7** [comment]
Hi @realHablex ,
are you using this package in your angular application?

**Comment by realHablex** [comment]
Hi,
lol yes, of course! My company uses this package to help develop angular components that are friendly to screen-readers and other accessibility needs. 
It would be great if you could publish new versions with peerdependencies for angular 8 and 9 on npm

**Comment by hassam7** [comment]
sure. I will update the peerdependencies and update the package this weekend.

**Comment by realHablex** [comment]
awesome thanks!
